<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>N.LMS.Manager.Learning.Service</AssemblyName>
    <RootNamespace>N.LMS.Manager.Learning.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Interface\N.LMS.Manager.Learning.Interface.csproj" />
    <ProjectReference Include="..\..\..\..\Common\N.LMS.Common.Interface\N.LMS.Common.Interface.csproj" />
    <ProjectReference Include="..\..\..\..\Ifx\N.LMS.Ifx.Interceptor\N.LMS.Ifx.Interceptor.csproj" />
    <ProjectReference Include="..\..\..\Accessor\Course\Interface\N.LMS.Accessor.Course.Interface.csproj" />
    <ProjectReference Include="..\..\..\Accessor\Enrollment\Interface\N.LMS.Accessor.Enrollment.Interface.csproj" />
    <ProjectReference Include="..\..\..\Accessor\Module\Interface\N.LMS.Accessor.Module.Interface.csproj" />
    <ProjectReference Include="..\..\..\Accessor\Lesson\Interface\N.LMS.Accessor.Lesson.Interface.csproj" />
  </ItemGroup>
</Project>
