<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\Nile.Database\Nile.Database.csproj" />
    <ProjectReference Include="..\..\Engines\Nile.Engines\Nile.Engines.csproj" />
    <ProjectReference Include="..\..\Nile.Utilities\Nile.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.1" />
  </ItemGroup>

</Project>
