<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>N.LMS.Utility.DateTime.Interface</AssemblyName>
    <RootNamespace>N.LMS.Utility.DateTime.Interface</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common\N.LMS.Common.Interface\N.LMS.Common.Interface.csproj" />
  </ItemGroup>
</Project>
