#!/usr/bin/env bash
set -euo pipefail

# Convenience script to start a local SQL Server (Docker) and run DbUp migrations/seeds
# Usage: ./run-seed.sh [SA_PASSWORD]

SQL_CONTAINER_NAME=${SQL_CONTAINER_NAME:-nile-sql}
SA_PASSWORD=${1:-${SA_PASSWORD:-YourDevP@ssw0rd!}}
SQL_HOST=${SQL_HOST:-localhost}
SQL_PORT=${SQL_PORT:-1433}
SQL_CONN="Server=${SQL_HOST},${SQL_PORT};Database=NileDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DBUP_PROJECT_DIR="$SCRIPT_DIR"

# Optional: TARGET_SCHOOL_ID environment variable. If set, create a small SQL script
# that assigns any existing Subjects with NULL SchoolId to the provided GUID so DbUp
# will embed and run it during the build/run step.
if [ ! -z "${TARGET_SCHOOL_ID:-}" ]; then
  echo "Target SchoolId provided: ${TARGET_SCHOOL_ID}. Creating temporary DbUp script..."
  mkdir -p "${DBUP_PROJECT_DIR}/Scripts/001"
  TMP_SQL_FILE="${DBUP_PROJECT_DIR}/Scripts/001/011.SetSubjectSchoolId_${TARGET_SCHOOL_ID}.sql"
  cat > "$TMP_SQL_FILE" <<SQL
-- 011.SetSubjectSchoolId_${TARGET_SCHOOL_ID}.sql
-- Auto-generated by run-seed.sh to set SchoolId for existing Subjects
PRINT 'Setting SchoolId for existing Subjects to ${TARGET_SCHOOL_ID} (auto-generated)';
IF EXISTS (SELECT 1 FROM dbo.Subjects WHERE SchoolId IS NULL)
BEGIN
    UPDATE dbo.Subjects SET SchoolId = '${TARGET_SCHOOL_ID}' WHERE SchoolId IS NULL;
END
SQL
  echo "Created $TMP_SQL_FILE"
  CLEANUP_TMP_SQL=1
fi

echo "Using SQL container name: ${SQL_CONTAINER_NAME}"

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is not installed or not running. Please install/start Docker and retry." >&2
  exit 1
fi

# Start container if not present
if [ "$(docker ps -q -f name=^/${SQL_CONTAINER_NAME}$)" = "" ]; then
  if [ "$(docker ps -aq -f name=^/${SQL_CONTAINER_NAME}$)" != "" ]; then
    echo "Removing existing stopped container ${SQL_CONTAINER_NAME}"
    docker rm "${SQL_CONTAINER_NAME}"
  fi
  echo "Starting SQL Server container ${SQL_CONTAINER_NAME} with SA_PASSWORD='${SA_PASSWORD}'..."
  docker run -e 'ACCEPT_EULA=Y' -e "SA_PASSWORD=${SA_PASSWORD}" -p ${SQL_PORT}:1433 --name "${SQL_CONTAINER_NAME}" -d mcr.microsoft.com/mssql/server:2022-latest
else
  echo "SQL Server container ${SQL_CONTAINER_NAME} already running."
fi

# Wait for SQL Server to report readiness (max ~3 minutes)
echo "Waiting for SQL Server to be ready (this can take up to 2 minutes)..."
ready=0
for i in {1..90}; do
  if docker logs "${SQL_CONTAINER_NAME}" 2>/dev/null | grep -q "SQL Server is now ready for client connections"; then
    ready=1
    break
  fi
  sleep 2
done

if [ "$ready" -ne 1 ]; then
  echo "Timed out waiting for SQL Server to start. Check the container logs: docker logs ${SQL_CONTAINER_NAME}" >&2
  exit 1
fi

echo "SQL Server is ready. Running DbUp..."

export SqlServerConnectionString="${SQL_CONN}"

# Run DbUp project to apply migrations/seeds
pushd "${DBUP_PROJECT_DIR}" >/dev/null
echo "Building DbUp project..."
dotnet build --nologo
echo "Running DbUp..."
dotnet run --verbosity minimal
popd >/dev/null

# Clean up temporary script if we created one
if [ "${CLEANUP_TMP_SQL:-0}" -eq 1 ]; then
  echo "Cleaning up temporary DbUp script..."
  rm -f "${TMP_SQL_FILE}"
fi

echo "DbUp run complete. Verify tables: SELECT TOP 10 * FROM dbo.SubLevels;"
